name: napari-isbem-env
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - python=3.11
 - pyqt
 - napari
 - numpy
 - scipy
 - scikit-image
 - scikit-learn
 - napari-ome-zarr
 - napari-tiff
 - opencv
 - SimpleITK
 - pip
