site_name: napari-isbem
site_url: https://FrancisCrickInstitute.github.io/napari-isbem
site_description: A napari plugin to allow targeted acquisition for SBF-SEM imaging.
nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage:
    - Targeting: targeting.md
    - Acquisition: acquisition.md
    - Registration: registration.md
  - Developer guide:
    - File structure: file_structure.md
    - Storing layers: storing_layers.md
    - SBEMimage integration: sbemimage_integration.md
    - ROI coordinates: roi_coordinates.md
    - Registration limitations: registration_limitations.md
    - Deployment: deployment.md
theme:
  name: material
plugins:
  - search
